---
resources:
- name: otp-builder-repo
  type: git
  source:
    uri: https://github.com/pailakka/concourse-build-test.git


- name: otp-builder-image
  type: docker-image
  source:
    repository: teemupel/otp-builder-image
    username: teemupel
    password: <asd>
jobs:
- name: build-otp-builder-image
  plan:
  - get: otp-builder-repo
    trigger: true  
  - put: otp-builder-image
    params: 
      build: otp-builder-repo/tools/builder

- name: build-otp-prod
  plan:
  - get: otp-builder-repo
    passed: [build-otp-builder-image]
  - get: otp-builder-image
    passed: [build-otp-builder-image]
    trigger: true
  - aggregate:
    - task: load-hsl-gtfs
      file: otp-builder-repo/tasks/load-hsl-gtfs-task.yaml
    - task: load-hsl-osm
      file: otp-builder-repo/tasks/load-hsl-osm-task.yaml
  - task: list files
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}

      inputs:
      - name: source-data
      run:
        path: find
        args: ["."]