---
resources:
- name: otp-builder-repo
  type: git
  source:
    uri: https://github.com/pailakka/concourse-build-test.git

- name: otp-builder-image
  type: docker-image
  source:
    repository: pailakka/otp-builder-image

jobs:
- name: build-otp-builder-image
  plan:
  - get: otp-builder-repo
  - put: otp-builder-image
    params: {build: tools/builder}

- name: build-otp-prod
  plan:
  - get: otp-builder-repo    
  - aggregate:
    - task: load-hsl-gtfs
      file: tasks/load-hsl-gtfs-task.yml
    - task: load-hsl-osm
      file: tasks/load-hsl-osm-task.yml
  - task: list files
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}

      inputs:
      - name: source-data

      run:
        path: ls
        args: [router-data/*]