---
platform: linux

outputs:
- name: source-data

inputs:
- name: otp-builder-repo

image_resource:
  type: docker-image
  source: {repository: teemupel/otp-builder-image}

run:
  path: parallel   -a 
  args: ["--eta","--progress","-a","./otp-builder-repo/scripts/dataload/load_source_data.sh"]