---
platform: linux

outputs:
- name: source-data

image_resource:
  type: docker-image
  source: {repository: busybox}

run:
  path: wget
  args: ["-O./source-data/hsl.osm.pbf","http://dev.hsl.fi/osm.hsl/hsl.osm.pbf"]