---
platform: linux

outputs:
- name: source-data

inputs:
- name: otp-builder-repo

image_resource:
  type: docker-image
  source: {repository: teemupel/otp-builder-image}

run:
  path: /bin/ash
  args: ["./otp-builder-repo/scripts/dataload/source_data_loader.sh"]