---
platform: linux

outputs:
- name: source-data

image_resource:
  type: docker-image
  source: {repository: busybox}

run:
  path: wget
  args: ["-O ./source-data/hsl.zip","http://dev.hsl.fi/gtfs/hsl.zip"]